### ISSUE TITLE
Built in rule WHITE_SPACE not highlighted

### ISSUE THREAD

**Issue by Mark1626** [Xoronic/pest-Syntax-Highlighting-for-vscode#2]
The built-in rule `WHITE_SPACE` is not being highlighted.

**Comment by Xoronic** [comment]
Thanks for creating an issue!

I could not reproduce it, however. It seems to highlight just fine for me:

![image](https://user-images.githubusercontent.com/30958364/60332587-72676180-9997-11e9-8b2d-314b07b52ce9.png)

It would be of great help if you could share the specific code that did not highlight properly.

**Comment by Mark1626** [comment]
Sorry, seems to be the theme, that messed with the highlighting.

In abyss:
<img width="355" alt="abyss" src="https://user-images.githubusercontent.com/20227996/60349426-33f59500-99df-11e9-9ed0-3bfb42871522.png">

In solarized light
<img width="330" alt="solarized_light" src="https://user-images.githubusercontent.com/20227996/60349437-39eb7600-99df-11e9-98ef-bb63800ab359.png">

Closing the issue, Thanks
